export enum PageRoutes {
  LOGIN = 'login',
  HOME = 'home',
  PROFILE = 'profile',
  ACCOUNT_AND_SECURITY = 'account-and-security',
  THEME_AND_BACKGROUND = 'theme-and-background',
  AVATAR_BACKGROUND = 'avatar-background',
  NOTIFICATION_AND_SOUND = 'notification-and-sound',
  PRIVACY_RIGHTS = 'privacy-rights',
  REPORT_PROBLEMS = 'report-problems',
  CONTACT_AND_SUPPORT = 'contact-and-support',
  TERMS_AND_POLICIES = 'terms-and-policies',
  PERSONAL_INFO = 'personal-info',
  APP_LOCK_SETTINGS = 'app-lock-settings',
  CHANGE_PASSWORD = 'change-password',
  BADGE_COLLECTION = 'badge-collection',
  PERSONAL_DIARY = 'personal-diary',
  CLASS_GROUP = 'class-group',
  FAMILY_GROUP = 'family-group',
  SCHOOL_GROUP = 'school-group',
  CHATBOT = 'chatbot',
  FRIENDS = 'friends',
  RANK = 'rank',
  PARENT_DASHBOARD = 'parent-database',
  TEACHER_DASHBOARD = 'teacher-dashboard',
}
