export enum StorageKey {
  AUTH_DATA = 'AUTH_DATA',
  LANGUAGE = 'LANGUAGE',
  ACCOUNT_HISTORY = 'ACCOUNT_HISTORY',
  CURRENT_APP_VERSION = 'CURRENT_APP_VERSION',
  FIREBASE_DEVICE_TOKEN = 'FIREBASE_DEVICE_TOKEN',
  ENABLE_BIOMETRIC = 'ENABLE_BIOMETRIC',
}
