export enum TranslateKeys {
  // COMMON
  COMMON_APP_NAME = 'COMMON.app_name',
  COMMON_COPYRIGHT = 'COMMON.copyright',
  COMMON_ENGLISH = 'COMMON.english',
  COMMON_VIETNAMESE = 'COMMON.vietnamese',

  // HOME
  HOME_WELCOME_TITLE = 'HOME.welcome_title',
  HOME_WELCOME_SUBTITLE = 'HOME.welcome_subtitle',

  // TASK
  TASK_SUBTITLE = 'TASK.subtitle',

  // RANK PAGE
  RANK_POSITION = 'RANK.position',
  RANK_NICKNAME = 'RANK.nickname',
  RANK_POINTS = 'RANK.points',
  RANK_POINTS_HEADER = 'RANK.points_header',
  BADGE_NEW = 'RANK.badge_new',

  // TITLE
  TITLE_PHONE = 'TITLE.phone',
  TITLE_EMAIL = 'TITLE.email',
  TITLE_PASSWORD = 'TITLE.password',
  TITLE_NEW_PASSWORD = 'TITLE.new_password',
  TITLE_CONFIRM_PASSWORD = 'TITLE.confirm_password',
  TITLE_LOGIN = 'TITLE.login',
  TITLE_LOGOUT = 'TITLE.logout',
  TITLE_REMEMBER_ME = 'TITLE.remember_me',
  TITLE_DATA_UPDATING = 'TITLE.data_updating',
  TITLE_INPUT_PIN = 'TITLE.input_pin',
  TITLE_AUTH_USER_TITLE = 'TITLE.auth_user_title',
  TITLE_AUTH_BIOMETRIC_UNLOCK_APP = 'TITLE.auth_biometric_unlock_app',
  TITLE_VERSION = 'TITLE.version',
  TITLE_HOME = 'TITLE.home',
  TITLE_PROFILE = 'TITLE.profile',
  TITLE_DASHBOARD = 'TITLE.dashboard',
  TITLE_CHATBOT = 'TITLE.chatbot',
  TITLE_RANK = 'TITLE.rank',
  TITLE_MENU = 'TITLE.menu',
  TITLE_VIEW_PROFILE_PAGE = 'TITLE.view_profile_page',
  TITLE_BADGE_COLLECTION = 'TITLE.badge_collection',
  TITLE_FAMILY_PAGE = 'TITLE.family_page',
  TITLE_CLASS_GROUP = 'TITLE.class_group',
  TITLE_SCHOOL_GROUP = 'TITLE.school_group',
  TITLE_FRIENDS = 'TITLE.friends',
  TITLE_TOTAL_FRIENDS = 'TITLE.total_friends',
  TITLE_CLOSE_FRIENDS = 'TITLE.close_friends',
  TITLE_ADD_FRIEND = 'TITLE.add_friend',
  TITLE_SEARCH_FRIENDS = 'TITLE.search_friends',
  TITLE_ACHIEVEMENTS = 'TITLE.achievements',
  TITLE_YOUR_RANK = 'TITLE.your_rank',
  TITLE_YOUR_ACHIEVEMENTS = 'TITLE.your_achievements',
  TITLE_THEME_AND_BACKGROUND = 'TITLE.theme_and_background',
  TITLE_NOTIFICATION_AND_SOUND = 'TITLE.notification_and_sound',
  TITLE_LANGUAGE = 'TITLE.language',
  TITLE_ACCOUNT_AND_SECURITY = 'TITLE.account_and_security',
  TITLE_PRIVACY_RIGHTS = 'TITLE.privacy_rights',
  TITLE_REPORT_PROBLEMS = 'TITLE.report_problems',
  TITLE_CONTACT_AND_SUPPORT = 'TITLE.contact_and_support',
  TITLE_TERMS_AND_POLICIES = 'TITLE.terms_and_policies',
  TITLE_THEME = 'TITLE.theme',
  TITLE_THEME_LIGHT = 'TITLE.theme_light',
  TITLE_THEME_DARK = 'TITLE.theme_dark',
  TITLE_THEME_SYSTEM = 'TITLE.theme_system',
  TITLE_TEXT_SIZE = 'TITLE.text_size',
  TITLE_TEXT_SIZE_SMALL = 'TITLE.text_size_small',
  TITLE_TEXT_SIZE_MEDIUM = 'TITLE.text_size_medium',
  TITLE_TEXT_SIZE_LARGE = 'TITLE.text_size_large',
  TITLE_TEXT_SIZE_BIG_SIZE = 'TITLE.text_size_big_size',
  TITLE_AVATAR = 'TITLE.avatar',
  TITLE_BACKGROUND = 'TITLE.background',
  TITLE_DEFAULT = 'TITLE.default',
  TITLE_BACKGROUND_SOUND = 'TITLE.background_sound',
  TITLE_TOUCH_SOUND = 'TITLE.touch_sound',
  TITLE_NOTIFICATION_SOUND = 'TITLE.notification_sound',
  TITLE_RELOAD_SOUND = 'TITLE.reload_sound',
  TITLE_LOADING_SOUND = 'TITLE.loading_sound',
  TITLE_MESSAGE_SOUND = 'TITLE.message_sound',
  TITLE_SUCCESS_SOUND = 'TITLE.success_sound',
  TITLE_FAILED_SOUND = 'TITLE.failed_sound',
  TITLE_MUSIC = 'TITLE.music',
  TITLE_NOTIFICATION = 'TITLE.notification',
  TITLE_ON = 'TITLE.on',
  TITLE_OFF = 'TITLE.off',
  TITLE_SHOW = 'TITLE.show',
  TITLE_HIDE = 'TITLE.hide',
  TITLE_BIRTHDAY = 'TITLE.birthday',
  TITLE_BIRTHDAY_NOTIFICATION = 'TITLE.birthday_notification',
  TITLE_LOCK_APP = 'TITLE.lock_app',
  TITLE_LOGIN_BY_BIOMETRIC = 'TITLE.login_by_biometric',
  TITLE_CHANGE_PASSWORD = 'TITLE.change_password',
  TITLE_PERSONAL_INFO = 'TITLE.personal_info',
  TITLE_SETUP_LOCK_APP_PIN = 'TITLE.setup_lock_app_pin',
  TITLE_CHANGE_LOCK_APP_PIN = 'TITLE.change_lock_app_pin',
  TITLE_AUTO_LOCK_APP = 'TITLE.auto_lock_app',
  TITLE_UNLOCK_APP_BIOMETRIC = 'TITLE.unlock_app_biometric',
  TITLE_ENABLE_VIEW_AND_COMMENT = 'TITLE.enable_view_and_comment',
  TITLE_BLOCK_AND_HIDDEN = 'TITLE.block_and_hidden',
  TITLE_AUTO_LOCK_IMMEDIATELY = 'TITLE.auto_lock_immediately',
  TITLE_AUTO_LOCK_30_SECONDS = 'TITLE.auto_lock_30_seconds',
  TITLE_AUTO_LOCK_1_MINUTE = 'TITLE.auto_lock_1_minute',
  TITLE_AUTO_LOCK_5_MINUTES = 'TITLE.auto_lock_5_minutes',
  TITLE_AUTO_LOCK_15_MINUTES = 'TITLE.auto_lock_15_minutes',
  TITLE_AUTO_LOCK_30_MINUTES = 'TITLE.auto_lock_30_minutes',
  TITLE_ENTER_NEW_PIN = 'TITLE.enter_new_pin',
  TITLE_CONFIRM_NEW_PIN = 'TITLE.confirm_new_pin',
  TITLE_ENTER_CURRENT_PIN = 'TITLE.enter_current_pin',

  // VALIDATE
  VALIDATE_PHONE_REQUIRED = 'VALIDATE.phone_required',
  VALIDATE_PASS_REQUIRED = 'VALIDATE.password_required',
  VALIDATE_NEW_PASS_REQUIRED = 'VALIDATE.new_password_required',
  VALIDATE_CONFIRM_PASS_REQUIRED = 'VALIDATE.confirm_password_required',
  VALIDATE_PASS_MIN_LENGTH = 'VALIDATE.password_min_length',
  VALIDATE_PASS_MATCH = 'VALIDATE.passwords_not_match',

  // ALERT
  ALERT_DEFAULT_HEADER = 'ALERT.default_header',
  ALERT_ERROR_HEADER = 'ALERT.error_header',
  ALERT_ERROR_SYSTEM_HEADER = 'ALERT.error_system_header',
  ALERT_ACCESS_PERMISSION_NOTIFICATION = 'ALERT.access_permission_notification_alert',
  ALERT_CONFIRM_LOGOUT = 'ALERT.confirm_logout_alert',

  // BUTTON TITLES
  BUTTON_CONFIRM = 'BUTTON_TITLES.confirm',
  BUTTON_CANCEL = 'BUTTON_TITLES.cancel',
  BUTTON_OPEN_SETTING = 'BUTTON_TITLES.open_settings',
  BUTTON_OK = 'BUTTON_TITLES.ok',
  BUTTON_CLOSE = 'BUTTON_TITLES.close',
  BUTTON_CURRENT = 'BUTTON_TITLES.current',
  BUTTON_SET_AS_CURRENT = 'BUTTON_TITLES.set_as_current',
  BUTTON_UPDATE = 'BUTTON_TITLES.update',
  BUTTON_EXECUTE = 'BUTTON_TITLES.execute',
  BUTTON_COMPLETE = 'BUTTON_TITLES.complete',

  // TOAST
  TOAST_ERROR_HEADER = 'TOAST.error_header',
  TOAST_SUCCESS_HEADER = 'TOAST.success_header',
  TOAST_INFO_HEADER = 'TOAST.info_header',
  TOAST_WARNING_HEADER = 'TOAST.warning_header',
  TOAST_AUTH_FAILED = 'TOAST.auth_failed',
  TOAST_AUTH_BY_PASSWORD = 'TOAST.auth_by_password',
  TOAST_NETWORK_ONLINE = 'TOAST.network_online',
  TOAST_NETWORK_OFFLINE = 'TOAST.network_offline',
  TOAST_CHANGE_PASS_SUCCESS = 'TOAST.password_changed_success',
  TOAST_TASK_COMPLETE_SUCCESS = 'TOAST.task_complete_success',
  TOAST_TASK_COMPLETE_ERROR = 'TOAST.task_complete_error',
  TOAST_ANSWER_ALL_QUESTIONS = 'TOAST.answer_all_questions',

  // ERROR
  ERROR_NETWORK = 'ERROR.network',
  ERROR_BAD_REQUEST = 'ERROR.bad_request',
  ERROR_UNAUTHORIZED = 'ERROR.unauthorized',
  ERROR_FORBIDDEN = 'ERROR.forbidden',
  ERROR_NOT_FOUND = 'ERROR.not_found',
  ERROR_SERVER = 'ERROR.server',
  ERROR_UNKNOWN = 'ERROR.unknown',
  ERROR_SERVER_CONNECTION = 'ERROR.server_connection',
  ERROR_INVALID_CURRENT_PASS = 'ERROR.invalid_current_password',

  // WARNING
  WARNING_APP_LOCK = 'WARNING.app_lock',
}
